/**
 * Automatic Dynamic SEO Engine.
 *
 * Every route gets a base title/description; keywords are auto-generated by
 * extracting meaningful terms from that copy (no manual keyword list to
 * maintain per page). New routes automatically fall back to a sensible
 * default so nothing ever ships without meta tags.
 */

interface RouteMeta {
  title: string;
  description: string;
}

const SITE_NAME = "Global AI Hub";

const STOPWORDS = new Set([
  "the", "and", "for", "with", "your", "you", "our", "are", "from", "into",
  "that", "this", "all", "a", "an", "to", "of", "in", "on", "is", "it",
  "by", "or", "as", "be", "at", "we", "us",
]);

export function generateKeywords(title: string, description: string, extra: string[] = []): string[] {
  const text = `${title} ${description} ${extra.join(" ")}`.toLowerCase();
  const words = text
    .split(/[^a-z0-9+]+/)
    .filter((w) => w.length > 2 && !STOPWORDS.has(w));
  return Array.from(new Set([...extra.map((e) => e.toLowerCase()), ...words])).slice(0, 15);
}

const ROUTE_META: Record<string, RouteMeta> = {
  "/": {
    title: `${SITE_NAME} — The Entire AI Universe, Personalized for You`,
    description: "Discover, build, and scale with 2,400+ AI tools, breaking model news, and curated resources for engineers, researchers, and founders.",
  },
  "/tools": {
    title: `AI Tools Directory | ${SITE_NAME}`,
    description: "Browse and compare thousands of AI tools across every category, with real-time ratings and community reviews.",
  },
  "/news": {
    title: `AI News & Breaking Model Updates | ${SITE_NAME}`,
    description: "Stay ahead with the latest AI model releases, research breakthroughs, and industry news, updated daily.",
  },
  "/ai-video-studio": {
    title: `AI Video Studio | ${SITE_NAME}`,
    description: "Generate stunning AI-powered videos with our creative studio, built for marketers and content creators.",
  },
  "/models": {
    title: `AI Model Explorer | ${SITE_NAME}`,
    description: "Compare leading AI models by capability, pricing, and benchmark performance in one place.",
  },
  "/jobs": {
    title: `AI Jobs Board | ${SITE_NAME}`,
    description: "Find your next role in AI research, engineering, and product — curated job listings updated daily.",
  },
  "/marketplace": {
    title: `AI Marketplace | ${SITE_NAME}`,
    description: "Buy and sell AI tools, prompts, and integrations in a trusted marketplace built for the AI economy.",
  },
  "/gigs": {
    title: `AI Freelance Gigs | ${SITE_NAME}`,
    description: "Hire vetted AI freelancers or find your next gig — from prompt engineering to model fine-tuning.",
  },
  "/roi-calculator": {
    title: `AI ROI Calculator | ${SITE_NAME}`,
    description: "Estimate the return on investment of adopting AI tools for your team or business in seconds.",
  },
  "/pricing": {
    title: `Pricing & Plans | ${SITE_NAME}`,
    description: "Choose the plan that fits your AI journey — pay instantly with USDT via secure crypto escrow checkout.",
  },
  "/playground": {
    title: `AI Sandbox & No-Code Builder | ${SITE_NAME}`,
    description: "Experiment with AI code execution and build no-code AI widgets instantly in your browser sandbox.",
  },
  "/login": {
    title: `Sign In | ${SITE_NAME}`,
    description: "Sign in to your Global AI Hub account to access your dashboard, sandbox, and rewards.",
  },
  "/signup": {
    title: `Create Your Account | ${SITE_NAME}`,
    description: "Join 50,000+ researchers and builders discovering, testing, and building with AI tools.",
  },
  "/dashboard": {
    title: `Your Dashboard | ${SITE_NAME}`,
    description: "Track your Hub Points, rewards, referrals, and personalized AI tool recommendations.",
  },
  "/admin": {
    title: `Super Admin Console | ${SITE_NAME}`,
    description: "Private operations console for monitoring live traffic, revenue, and platform health.",
  },
};

const DEFAULT_META: RouteMeta = {
  title: SITE_NAME,
  description: "Discover, build, and scale with the entire AI universe — tools, news, marketplace, and more.",
};

export function getRouteMeta(pathname: string): { title: string; description: string; keywords: string[] } {
  const base = ROUTE_META[pathname] ?? DEFAULT_META;
  const keywords = generateKeywords(base.title, base.description, ["AI tools", "artificial intelligence", "global ai hub"]);
  return { ...base, keywords };
}
