import { pgTable, text, boolean, timestamp, integer, uuid, numeric } from "drizzle-orm/pg-core";

export const scrapedGigs = pgTable("scraped_gigs", {
  id: uuid("id").primaryKey().defaultRandom(),
  externalId: text("external_id").notNull(),
  source: text("source").notNull(),
  sourceUrl: text("source_url").notNull(),
  title: text("title").notNull(),
  sellerName: text("seller_name").notNull(),
  sellerUsername: text("seller_username").notNull().default(""),
  sellerProfileUrl: text("seller_profile_url").notNull().default(""),
  sellerEmail: text("seller_email"),
  description: text("description").notNull(),
  category: text("category").notNull(),
  originalPrice: numeric("original_price", { precision: 10, scale: 2 }).notNull(),
  ourPrice: numeric("our_price", { precision: 10, scale: 2 }).notNull(),
  rating: numeric("rating", { precision: 3, scale: 1 }).notNull().default("5.0"),
  reviewCount: integer("review_count").notNull().default(0),
  deliveryDays: integer("delivery_days").notNull().default(3),
  imageUrl: text("image_url"),
  tags: text("tags").array().notNull().default([]),
  status: text("status").notNull().default("draft"),
  slug: text("slug").notNull(),
  metaTitle: text("meta_title").notNull(),
  metaDescription: text("meta_description").notNull(),
  hashtags: text("hashtags").array().notNull().default([]),
  notificationSent: boolean("notification_sent").notNull().default(false),
  notificationSentAt: timestamp("notification_sent_at", { withTimezone: true }),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
